DROP DATABASE IF EXISTS Bank;
CREATE DATABASE Bank;
USE Bank;


DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS CUSTOMER;


CREATE TABLE CUSTOMER (
  CUSTOMER_ID INT NOT NULL,
  First_name VARCHAR(40),
  Last_name VARCHAR(40),
  PRIMARY KEY (CUSTOMER_ID)
) ENGINE = INNODB;


INSERT INTO CUSTOMER(CUSTOMER_ID, First_name, Last_name)
VALUES (1, "Viivi", "Tervola");
INSERT INTO CUSTOMER(CUSTOMER_ID, First_name, Last_name)
VALUES (2, "Bob", "Smith");
INSERT INTO CUSTOMER(CUSTOMER_ID, First_name, Last_name)
VALUES (3, "Ilmari", "Kolehmainen");
INSERT INTO CUSTOMER(CUSTOMER_ID, First_name, Last_name)
VALUES (4, "Gunilla", "Jespersen");
INSERT INTO CUSTOMER(CUSTOMER_ID, First_name, Last_name)
VALUES (5, "Taisto", "Kukkonen");

CREATE TABLE ACCOUNT (
  ID INT NOT NULL,
  Balance DECIMAL (10, 2) NOT NULL,
  Owner INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (Owner) REFERENCES CUSTOMER(CUSTOMER_ID)
) ENGINE = INNODB;

INSERT INTO ACCOUNT(ID, Balance, Owner)
VALUES (100, 1000.00, 1);
INSERT INTO ACCOUNT(ID, Balance, Owner)
VALUES (101, 2800.00, 2);
INSERT INTO ACCOUNT(ID, Balance, Owner)
VALUES (102, 1342.57, 2);
INSERT INTO ACCOUNT(ID, Balance, Owner)
VALUES (103, 760.00, 3);
INSERT INTO ACCOUNT(ID, Balance, Owner)
VALUES (104, -12.54, 4);
INSERT INTO ACCOUNT(ID, Balance, Owner)
VALUES (105, 138740.69, 2);
INSERT INTO ACCOUNT(ID, Balance, Owner)
VALUES (106, 224.75, 5);